### ISSUE TITLE
Required headers aren't being set

### ISSUE THREAD

**Issue by mattstratton** [mrchief/mixlib-auth-csharp#1]
I discovered that two headers that the Chef server now requires are not set properly by this libary, namely:

`X-Chef-Version`
and
`X-Ops-Sign` (is set by the library, but to an invalid version...it should be `version=1.0`)

I'll try to get a PR in to fix them. I think that the best solution is probably to have these headers have a default, but be able to be overridden, especially the chef-version? Thoughts?

**Comment by mrchief** [comment]
Looks good! Thanks for getting this in!

**Comment by mrchief** [comment]
V1.1.0 out now!
